package fr.emse.ai.search.simple;

public class FarmerState {
    
    private int farmerLeft;
    private int cabbageLeft;
    private int wolfLeft;
    private int goatLeft;
    private int farmerRight;
    private int cabbageRight;
    private int wolfRight;
    private int goatRight;

    public FarmerState(int farmerLeft, int cabbageLeft, int wolfLeft, int goatLeft, 
                       int farmerRight, int cabbageRight, int wolfRight, int goatRight) {
        this.farmerLeft = farmerLeft;
        this.farmerRight = farmerRight;
        this.cabbageLeft = cabbageLeft;
        this.cabbageRight = cabbageRight;
        this.wolfLeft = wolfLeft;
        this.wolfRight = wolfRight;
        this.goatLeft = goatLeft;
        this.goatRight = goatRight;
    }

    public int getFarmerLeft() { return farmerLeft; }

    public void setFarmerLeft(int farmerLeft) { this.farmerLeft = farmerLeft; }

    public int getCabbageLeft() { return cabbageLeft; }

    public void setCabbageLeft(int cabbageLeft) { this.cabbageLeft = cabbageLeft; }

    public int getWolfLeft() { return wolfLeft; }

    public void setWolfLeft(int wolfLeft) { this.wolfLeft = wolfLeft; }

    public int getGoatLeft() { return goatLeft; }

    public void setGoatLeft(int goatLeft) { this.goatLeft = goatLeft; }

    public int getFarmerRight() { return farmerRight; }

    public void setFarmerRight(int farmerRight) { this.farmerRight = farmerRight; }

    public int getCabbageRight() { return cabbageRight; }

    public void setCabbageRight(int cabbageRight) { this.cabbageRight = cabbageRight; }

    public int getWolfRight() { return wolfRight; }

    public void setWolfRight(int wolfRight) { this.wolfRight = wolfRight; }

    public int getGoatRight() { return goatRight; }

    public void setGoatRight(int goatRight) { this.goatRight = goatRight; }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;  // equals() function generated by Intellij default
        if (o == null || getClass() != o.getClass()) return false;

        FarmerState that = (FarmerState) o;

        if (farmerLeft != that.farmerLeft) return false;
        if (cabbageLeft != that.cabbageLeft) return false;
        if (wolfLeft != that.wolfLeft) return false;
        if (goatLeft != that.goatLeft) return false;
        if (farmerRight != that.farmerRight) return false;
        if (cabbageRight != that.cabbageRight) return false;
        if (wolfRight != that.wolfRight) return false;
        return goatRight == that.goatRight;
    }

    @Override
    public String toString() {
        return "FarmerState{" +
                "farmerLeft=" + farmerLeft +
                ", cabbageLeft=" + cabbageLeft +
                ", wolfLeft=" + wolfLeft +
                ", goatLeft=" + goatLeft +
                ", farmerRight=" + farmerRight +
                ", cabbageRight=" + cabbageRight +
                ", wolfRight=" + wolfRight +
                ", goatRight=" + goatRight +
                '}';
    }
}
